"""updating the user class

Revision ID: 0351de154e97
Revises: bf8e4c6e33a2
Create Date: 2022-12-26 00:00:42.370070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0351de154e97'
down_revision = 'bf8e4c6e33a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_username', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_username', ['username'])

    # ### end Alembic commands ###
